### ISSUE TITLE
Quick start tutorial failing on model creation

### ISSUE THREAD

**Issue by pzharrington** [facebookresearch/vissl#253]
Following the steps in [https://vissl.readthedocs.io/en/v0.1.5/getting_started.html](https://vissl.readthedocs.io/en/v0.1.5/getting_started.html), I get an error coming from model build process where vissl is trying to load weights from a file that does not exist. Checking default `config` file, I see `MODEL.WEIGHTS_INIT.PARAMS_FILE` is set to `""`, i.e., an empty string. However, using the `PathManager` from my `fvcore` installation (which came with installing `vissl` via `pip`) I see that `PathManager.exists("")` somehow evaluates to `True`. Then the line `if PathManager.exists(init_weights_path):` (line 380 in `vissl/trainer/train_task.py`) fails to prevent the model trying to load weights from an empty filename, and code errors out. 

## Instructions To Reproduce the Issue:
1. Install vissl as `pip install --user vissl` in the `pytorch:ngc-20.10` docker image 
2. Set up dataset config as described for imagenet_1k dataset (files stored in `/tmp/`)
3. Run the following:
```
python3 run_distributed_engines.py \
     hydra.verbose=true \
     config.DATA.TRAIN.DATASET_NAMES=[imagenet1k_tmp] \
     config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
     config.DATA.TRAIN.DATA_PATHS=["/tmp/train"] \
     config=quick_1gpu_resnet50_simclr \
     config.CHECKPOINT.DIR="/global/cscratch1/sd/pharring/vissl/checkpoints" \
     config.CHECKPOINT.AUTO_RESUME=true
     config.TENSORBOARD_SETUP.USE_TENSORBOARD=true
```
3. With `hydra.verbose=true`, lots of output so I will not include all irrelevant details. Initially some warnings from `PathManager` saying:    
```
[PathManager] Attempting to register prefix 'http://' from the following call stack:
  File "run_distributed_engines.py", line 166, in _distributed_worker
    process_main(cfg, dist_run_id, local_rank=local_rank, node_id=node_id)
  File "run_distributed_engines.py", line 159, in process_main
    hook_generator=hook_generator,
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/engines/train.py", line 60, in train_main
    set_env_vars(local_rank, node_id, cfg)
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/utils/env.py", line 31, in set_env_vars
    PathManager.register_handler(HTTPURLHandler(), allow_override=True)
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/fvcore/common/file_io.py", line 288, in register_handler
    + "".join(traceback.format_stack(limit=5))

[PathManager] Prefix 'http://' is already registered by <class 'iopath.common.file_io.HTTPURLHandler'>. We will override the old handler. To avoid such conflicts, create a project-specific PathManager instead.
```
This same chatter appears for `ftp://` and `https://`, then a bunch of printouts of env variables and build settings, then the error with traceback:
```
INFO 2021-03-24 22:34:05,852 train_task.py: 378: Initializing model from: 
INFO 2021-03-24 22:34:05,852 util.py: 241: Broadcasting checkpoint loaded from 
Traceback (most recent call last):
  File "run_distributed_engines.py", line 194, in <module>
    hydra_main(overrides=overrides)
  File "run_distributed_engines.py", line 179, in hydra_main
    hook_generator=default_hook_generator,
  File "run_distributed_engines.py", line 123, in launch_distributed
    hook_generator=hook_generator,
  File "run_distributed_engines.py", line 166, in _distributed_worker
    process_main(cfg, dist_run_id, local_rank=local_rank, node_id=node_id)
  File "run_distributed_engines.py", line 159, in process_main
    hook_generator=hook_generator,
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/engines/train.py", line 102, in train_main
    trainer.train()
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/trainer/trainer_main.py", line 155, in train
    self.task.prepare(pin_memory=self.cfg.DATA.PIN_MEMORY)
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/trainer/train_task.py", line 634, in prepare
    self.base_model = self._build_model()
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/trainer/train_task.py", line 462, in _build_model
    model = self._restore_model_weights(model)
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/trainer/train_task.py", line 399, in _restore_model_weights
    append_prefix=append_prefix,
  File "/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl/utils/checkpoint.py", line 404, in init_model_from_weights
    state_dict_key_name in state_dict.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
```
## Expected behavior:
Model should build successfully, without trying to loading in any weights upon initialization. I could be doing something wrong, but having trouble seeing where, as I followed the quick start steps closely!

## Environment:
Full environment shown below:
```
--------------------  -----------------------------------------------------------------------------------------------------------
sys.platform          linux
Python                3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
numpy                 1.19.1
Pillow                8.0.1
vissl                 0.1.5 @/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/vissl
GPU available         True
GPU 0,1               Tesla V100-SXM2-16GB
CUDA_HOME             /usr/local/cuda
TORCH_CUDA_ARCH_LIST  5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX
torchvision           0.8.0a0 @/opt/conda/lib/python3.6/site-packages/torchvision
hydra                 1.0.6 @/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/hydra
classy_vision         0.6.0.dev @/global/homes/p/pharring/.local/cori/pytorch_ngc_20.10/lib/python3.6/site-packages/classy_vision
tensorboard           1.15.0
apex                  0.1 @/opt/conda/lib/python3.6/site-packages/apex
cv2                   3.4.1
PyTorch               1.7.0a0+7036e91 @/opt/conda/lib/python3.6/site-packages/torch
PyTorch debug build   False
--------------------  -----------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

CPU info:
-------------------  ----------------------------------------
Architecture         x86_64
CPU op-mode(s)       32-bit, 64-bit
Byte Order           Little Endian
CPU(s)               80
On-line CPU(s) list  0-79
Thread(s) per core   2
Core(s) per socket   20
Socket(s)            2
NUMA node(s)         2
Vendor ID            GenuineIntel
CPU family           6
Model                85
Model name           Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
Stepping             4
CPU MHz              2400.000
CPU max MHz          3700.0000
CPU min MHz          1000.0000
BogoMIPS             4800.00
Virtualization       VT-x
L1d cache            32K
L1i cache            32K
L2 cache             1024K
L3 cache             28160K
NUMA node0 CPU(s)    0-19,40-59
NUMA node1 CPU(s)    20-39,60-79
-------------------  ----------------------------------------
```

**Comment by prigoyal** [comment]
Hi @pzharrington , thank you for reaching out about this. Take a look at the issue https://github.com/facebookresearch/vissl/issues/248 . fvcore dependency recently seems to have some changes which are leading to this issue. In VISSL, we will look into pinning the fvcore and iopath version in future.

**Comment by pzharrington** [comment]
Ah! I don't know how I overlooked that issue, as it's my exact situation. Thanks for the explanation.

**Comment by prigoyal** [comment]
also reported to fvcore developers here https://github.com/facebookresearch/iopath/issues/6 :)
