### ISSUE TITLE
Training SimCLR on 1-gpu with VISSL tutorial throws an error on training

### ISSUE THREAD

**Issue by gurlina** [facebookresearch/vissl#311]
When running [Training SimCLR on 1-gpu with VISSL](https://colab.research.google.com/drive/1Rt3Plt3ph84i1A-eolLFafybwjrBFxYe?usp=sharing) tutorial, I tried to kick-off the training using the following command:

```
!python3 run_distributed_engines.py \
    hydra.verbose=true \
    config=quick_1gpu_resnet50_simclr \
    config.DATA.TRAIN.DATA_SOURCES=[synthetic] \
    config.CHECKPOINT.DIR="./checkpoints" \
    +config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD=true
```
After outputting various configuration settings, the code has encountered an error while building a model:  

```
INFO 2021-05-04 02:13:10,704 train_task.py: 419: Building model....
INFO 2021-05-04 02:13:10,705 resnext.py:  63: ResNeXT trunk, supports activation checkpointing. Deactivated
INFO 2021-05-04 02:13:10,705 resnext.py:  83: Building model: ResNeXt50-1x64d-w1-BatchNorm2d
INFO 2021-05-04 02:13:11,316 model_helpers.py: 138: Using SyncBN group size: 1
INFO 2021-05-04 02:13:11,316 model_helpers.py: 153: Converting BN layers to PyTorch SyncBN
WARNING 2021-05-04 02:13:11,317 model_helpers.py: 159: Process groups not supported with PyTorch SyncBN currently. Traning will be slow. Please consider installing Apex for SyncBN.
INFO 2021-05-04 02:13:11,322 train_task.py: 378: Initializing model from: 
INFO 2021-05-04 02:13:11,323 util.py: 241: Broadcasting checkpoint loaded from 
Traceback (most recent call last):
  File "run_distributed_engines.py", line 194, in <module>
    hydra_main(overrides=overrides)
  File "run_distributed_engines.py", line 179, in hydra_main
    hook_generator=default_hook_generator,
  File "run_distributed_engines.py", line 123, in launch_distributed
    hook_generator=hook_generator,
  File "run_distributed_engines.py", line 166, in _distributed_worker
    process_main(cfg, dist_run_id, local_rank=local_rank, node_id=node_id)
  File "run_distributed_engines.py", line 159, in process_main
    hook_generator=hook_generator,
  File "/usr/local/lib/python3.7/dist-packages/vissl/engines/train.py", line 102, in train_main
    trainer.train()
  File "/usr/local/lib/python3.7/dist-packages/vissl/trainer/trainer_main.py", line 155, in train
    self.task.prepare(pin_memory=self.cfg.DATA.PIN_MEMORY)
  File "/usr/local/lib/python3.7/dist-packages/vissl/trainer/train_task.py", line 634, in prepare
    self.base_model = self._build_model()
  File "/usr/local/lib/python3.7/dist-packages/vissl/trainer/train_task.py", line 462, in _build_model
    model = self._restore_model_weights(model)
  File "/usr/local/lib/python3.7/dist-packages/vissl/trainer/train_task.py", line 399, in _restore_model_weights
    append_prefix=append_prefix,
  File "/usr/local/lib/python3.7/dist-packages/vissl/utils/checkpoint.py", line 404, in init_model_from_weights
    state_dict_key_name in state_dict.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
``` 

Upon inspection, I noticed that even though I didn't specify a path to pre-trained model weights, the code was still trying to call ```_restore_model_weights``` function, thus ultimately causing the ```NoneType``` error in ```init_model_from_weights``` function.  

Here's the output excerpt showing the settings for ```WEIGHTS_INIT``` key:  

```
           'WEIGHTS_INIT': {'APPEND_PREFIX': '',
                            'PARAMS_FILE': '',
                            'REMOVE_PREFIX': '',
                            'SKIP_LAYERS': ['num_batches_tracked'],
                            'STATE_DICT_KEY_NAME': 'classy_state_dict'}},
```

**Comment by prigoyal** [comment]
Hi @gurlina , thank you for reaching out. Take a look at the https://github.com/facebookresearch/vissl/issues/248#issuecomment-805357468 on this :) it is a known issue that's fixed in VISSL master but the new packages haven't been released yet.
