### ISSUE TITLE
Colab notebook issue

### ISSUE THREAD

**Issue by virisha22** [facebookresearch/vissl#326]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
Just using [this](https://colab.research.google.com/drive/1iigQmKL_DUuBLT6BqjrGXlW9ZIqKIFmt?usp=sharing) colab notebook
```
2. what exact command you run:
```
!python3 run_distributed_engines.py \
    hydra.verbose=true \
    config=supervised_1gpu_resnet_example \
    config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
    config.DATA.TRAIN.LABEL_SOURCES=[disk_folder] \
    config.DATA.TRAIN.DATASET_NAMES=[dummy_data_folder] \
    config.DATA.TRAIN.DATA_PATHS=[/content/dummy_data/train] \
    config.DATA.TRAIN.BATCHSIZE_PER_REPLICA=2 \
    config.DATA.TEST.DATA_SOURCES=[disk_folder] \
    config.DATA.TEST.LABEL_SOURCES=[disk_folder] \
    config.DATA.TEST.DATASET_NAMES=[dummy_data_folder] \
    config.DATA.TEST.DATA_PATHS=[/content/dummy_data/val] \
    config.DATA.TEST.BATCHSIZE_PER_REPLICA=2 \
    config.DISTRIBUTED.NUM_NODES=1 \
    config.DISTRIBUTED.NUM_PROC_PER_NODE=1 \
    config.OPTIMIZER.num_epochs=2 \
    config.OPTIMIZER.param_schedulers.lr.values=[0.01,0.001] \
    config.OPTIMIZER.param_schedulers.lr.milestones=[1] \
    config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD=true \
    config.CHECKPOINT.DIR="./checkpoints"
```
3. what you observed (including __full logs__):
```
####### overrides: ['hydra.verbose=true', 'config=supervised_1gpu_resnet_example', 'config.DATA.TRAIN.DATA_SOURCES=[disk_folder]', 'config.DATA.TRAIN.LABEL_SOURCES=[disk_folder]', 'config.DATA.TRAIN.DATASET_NAMES=[dummy_data_folder]', 'config.DATA.TRAIN.DATA_PATHS=[/content/dummy_data/train]', 'config.DATA.TRAIN.BATCHSIZE_PER_REPLICA=2', 'config.DATA.TEST.DATA_SOURCES=[disk_folder]', 'config.DATA.TEST.LABEL_SOURCES=[disk_folder]', 'config.DATA.TEST.DATASET_NAMES=[dummy_data_folder]', 'config.DATA.TEST.DATA_PATHS=[/content/dummy_data/val]', 'config.DATA.TEST.BATCHSIZE_PER_REPLICA=2', 'config.DISTRIBUTED.NUM_NODES=1', 'config.DISTRIBUTED.NUM_PROC_PER_NODE=1', 'config.OPTIMIZER.num_epochs=2', 'config.OPTIMIZER.param_schedulers.lr.values=[0.01,0.001]', 'config.OPTIMIZER.param_schedulers.lr.milestones=[1]', 'config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD=true', 'config.CHECKPOINT.DIR=./checkpoints', 'hydra.verbose=true']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py", line 513, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/omegaconf.py", line 590, in update
    root[key_] = {}
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 259, in __setitem__
    key=key, value=value, type_override=ConfigKeyError, cause=e
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'HOOKS' is not in struct
	full_key: config.HOOKS
	reference_type=Any
	object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_distributed_engines.py", line 194, in <module>
    hydra_main(overrides=overrides)
  File "run_distributed_engines.py", line 172, in hydra_main
    cfg = compose("defaults", overrides=overrides)
  File "/usr/local/lib/python3.7/dist-packages/hydra/experimental/compose.py", line 37, in compose
    with_log_configuration=False,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py", line 518, in _apply_overrides_to_config
    ) from ex
hydra.errors.ConfigCompositionException: Could not override 'config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD'.
To append to your config use +config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD=true
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Environment:

Provide your environment information using the following command:
Running the google colab notebook provided in the VISSL docs.

## When to expect Triage

VISSL devs and contributors aim to triage issues asap however, as a general guideline, we ask users to expect triaging in 1-2 weeks.

**Comment by QuentinDuval** [comment]
Hi @virisha22,

I had a look at the notebook and the tensorboard option is indeed not correct.
You can make it work by using `config.TENSORBOARD_SETUP.USE_TENSORBOARD=true` instead of `config.HOOKS.TENSORBOARD_SETUP.USE_TENSORBOARD=true`.

We need to adapt the notebook on our side to correct this.

CC: @prigoyal

**Comment by prigoyal** [comment]
ah, thank you for reporting this @virisha22 , the issue is due to the mismatch of the tutorial version and the vissl code version. Our current tutorials correspond to the `stable` VISSL version https://github.com/facebookresearch/vissl/tree/stable . I'll work on pointing the tutorial to the right code version to avoid such confusion. Our current tutorials are not updated to reflect all the changes between `stable` and `master` of VISSL. 

To unblock immediately, if you must use the master version of vissl, you can adapt the tutorial (install VISSL from source, not the package and adapt the changes to the `vissl/defaults.yaml` file).

Please let us know if there is anything else we can help with. Otherwise feel free to close this issue :)

**Comment by virisha22** [comment]
Oh thank you for the pointers, will close this.
